import React from 'react';

const GizlilikPolitikasiPage = () => (
  <div className="max-w-3xl mx-auto px-4 py-8">
    <br /><br /><br />
    <div className="prose prose-sm sm:prose lg:prose-lg xl:prose-xl">
      <p style={{ textAlign: 'center' }}><b>MAPPERX</b></p>
      <p style={{ textAlign: 'center' }}><b>KULLANICI SÖZLEŞMESİ VE GİZLİLİK KOŞULLARI</b></p>
      <p style={{ textAlign: 'center' }}><b>KULLANICI SÖZLEŞMESİ</b></p>
      <p>İşbu Kullanıcı Sözleşmesi, BİRİZ GLOBAL TEKNOLOJİ LTD. ŞTİ. ile <b>mapperx.com</b> adresinde yer alan siteye kullanıcı olarak kaydolan kişi arasında, Kullanıcı'nın Website ve Uygulama'yı kullanmasına yönelik olarak Website ve Uygulama'nın bulunduğu elektronik ortamda Kullanıcı tarafından onaylanması anında düzenlenmiştir.</p>
      <p><b>1. TANIMLAR</b></p>
      <p>İşbu Sözleşme'de yer alan;</p>
      <p>"<b>MAPPERX</b>", BİRİZ GLOBAL TEKNOLOJİ LTD. ŞTİ.'yi</p>
      <p>"<b>İçerik</b>", Website'de ve/veya Uygulama'da bulunan veya erişimi mümkün olan her türlü veriyi, bilgiyi, dosyayı, resimi, rakamı, görsel, yazınsal ve işitsel imgeleri,</p>
      <p>"<b>Kullanıcı</b>", Sözleşme'nin koşullarını kabul ederek Website'de yer alan İçerikler, uygulamalar ve Hizmet'ten yalnızca kendi dahili ihtiyaçları için yararlanacak medeni hakları kullanmaya ehil tüm gerçek ve tüzel kişileri,</p>
      <p>"<b>Hizmet</b>", MAPPERX tarafından bulut üzerinden Website ve Uygulama aracılığıyla Kullanıcı'ya Websitesi ve Uygulamada yer alan koşullarla ücretli veya ücretsiz olarak sunulacak iş uygulaması hizmetini/hizmetlerini,</p>
      <p>"<b>Sözleşme</b>", işbu Kullanıcı Sözleşmesini,</p>
      <p>"<b>Taraflar</b>", MAPPERX ve Kullanıcı'yı,</p>
      <p>"<b>Uygulama</b>", MAPPERX tarafından veya MAPPERX için geliştirilen; mali/telif hakları veya ticari tedavüle sunma hakları MAPPERX'e ait olan, Website veya mobil cihazlar üzerinden erişilen bulut tabanlı pv panel inceleme yazılımı,</p>
      <p>"<b>Website</b>", mapperx.com alan adı ve diğer alt alan adlarından ulaşılabilen, MAPPERX'in Sözleşme ile kapsamı belirlenen hizmetleri sunduğu diğer web sitelerini ifade eder.</p>
      <p><b>"Veri Merkezleri":</b> Kullanıcının bu Hizmetten yararlanabilmesi için Website, Uygulama, İçerik ve/veya Kullanıcı verilerinin barındırılacağı MAPPERX'e veya Üçüncü Şahıslara ait ve yer sağlayıcı faaliyet belgesine sahip, yurt içi ve/veya yurt dışındaki hosting siteleri/mahalleri anlamına gelir.</p>
      <p>"<b>Hizmet Sağlayıcılar</b> Bu Sözleşme kapsamındaki Hizmetlerin bir kısmını profesyonel olarak yerine getiren, mevzuat tarafından gerekmesi halinde sertifikaları olan yurt içi ve/veya yurt dışındaki Üçüncü Şahısları ifade eder.</p>
      <p><b>"Üçüncü Şahıs"</b> Bu Sözleşmenin tarafları dışında kalan gerçek kişi, şahıs veya sermaye şirketi, kurum, kuruluş, vakıf, dernek ve benzeri hukuki işlem ehliyetine sahip; yerli, yabancı bütün kamu ve özel "kişilerini" kapsamak üzere kullanılmıştır.</p>
      <p>"<b>Üçüncü Şahıs Yazılımları</b>" Mülkiyet hakları Üçüncü Şahıslara ait olan herhangi bir yazılım ürünü anlamına gelir.</p>
      <p><b>"Fikri Mülkiyet Hakları"</b> Sadece sayılanlarla sınırlı olmamak üzere her türlü patent, telif hakkı, ticari marka uygulamaları ve/veya diğer fikri mülkiyet hakları ve ilgili dokümantasyon hakları anlamına gelir.</p>
      <p><b>2. SÖZLEŞME'NİN KONUSU VE KAPSAMI</b></p>
      <p>2.1. İşbu Sözleşme, Website ve Uygulama üzerinden erişilen bulut tabanlı pv panel inceleme yazılımından Kullanıcı tarafından faydalanılmasına ve Website ve Uygulama'ya yüklenen verilere ilişkin koşul ve şartlar ile ilgili tarafların hak ve yükümlülüklerini düzenlemektedir.</p>
      <p>2.2. İşbu Sözleşme Kullanıcı'nın "Kullanıcı Sözleşmesini ve Gizlilik Koşullarını okudum ve onaylıyorum." kutucuğunu işaretleyerek elektronik ortamda kabulü ve/veya Uygulamayı kullanması ile yürürlüğe girecek olup; taraflarca Sözleşme'de belirtilen usuller doğrultusunda sona erdirilmediği sürece yürürlükte kalmaya devam edecektir. Kullanıcı işbu Sözleşme'yi kabul ederek, vereceği bilgilerin, Website ve Uygulama'da yer alan Hizmet'lerin sunulmasında kullanılacağını kabul ve beyan eder.</p>
      <p><b>3. TARAFLARIN HAK VE YÜKÜMLÜLÜKLERİ</b></p>
      <p>3.1. Kullanıcı, Uygulama'yı kullanabilmek için işbu Sözleşme'yi onaylaması gerektiğini bildiğini ve MAPPERX tarafından talep edilen bilgileri eksiksiz, güncel ve doğru bir şekilde sağladığını kabul, taahhüt ve beyan eder. Kullanıcı hesabının oluşturulması sırasında sağlanan bilgilerde herhangi bir değişiklik olması halinde, söz konusu bilgiler Kullanıcı tarafından derhal güncellenecektir. Bu bilgilerin Kullanıcı tarafından yanlış, eksik veya güncel olmayan şekilde temin edilmesi nedeniyle Website ya da Uygulama'ya erişim sağlanamamasından ve/veya bu nedenle oluşabilecek zararlardan MAPPERX'in herhangi bir sorumluluğu bulunmamaktadır.</p>
      <p>3.2. Kullanıcı, işbu Sözleşme'yi akdetmek için gereken hukuki ehliyete sahip bulunduğunu ve 18 yaşını doldurmuş olduğunu beyan eder. Aksi durumda yapılan tüm işlemler geçersiz olacaktır.</p>
      <p>3.3. Kullanıcı, Website ve Uygulama'yı yalnızca hukuka uygun amaçlarla kullanacağını, işbu Sözleşme, ekleri, yürürlükteki mevzuat ve Website'de öngörülen diğer hüküm ve koşullara uygun davranacağını kabul ve taahhüt eder. Kullanıcı, Uygulama ve Website'yi Üçüncü Şahıslara hizmet sunmak için yetkili olduğu sürece Üçüncü Şahıs adına kullanabilecektir. Kullanıcı bu kapsamda, söz konusu kişilerin de işbu Sözleşme ve kendisi için geçerli olan diğer tüm hükümlere uygun davranmasını sağlayacaktır.</p>
      <p>3.4. Kullanıcı'nın tek bir hesap tesis etmeye hakkı olup, söz konusu hesabının MAPPERX tarafından askıya alınması veya sona erdirilmesini takiben aynı Kullanıcı tarafından ikinci bir hesap açılması yasaktır. MAPPERX'in herhangi bir gerekçe göstermeksizin, tamamen kendi iradesine tabi olarak Kullanıcı hesabının açılmasını reddetme hakkı saklıdır.</p>
      <p>3.5. Website'ye erişim Kullanıcı tarafından e-posta adresi (veya kullanıcı adı) ve şifresi kullanılarak gerçekleştirilecektir. Website üzerinden söz konusu bilgilerin kullanımı ile gerçekleştirilen her türlü faaliyetin Kullanıcı tarafından gerçekleştirildiği kabul edilecek olup bu şifrenin kimseyle paylaşılmamasından, gizliliğinden ve güvenliğinden Kullanıcı sorumludur. İşbu şifre kullanılarak gerçekleştirilen tüm faaliyetlerden doğan her türlü yasal ve cezai sorumluluk Kullanıcı'ya ait olup Kullanıcı şifresinin yetkisiz kullanımı veya güvenliğin başka şekilde ihlalinden haberdar olur olmaz bu durumu derhal MAPPERX'e bildirmekle yükümlüdür.</p>
      <p>3.6. Kullanıcı, üçüncü bir kişiyi ("İzinli Kullanıcı") Uygulama'yı kullanması için yetkilendirebilir. Kullanıcı tarafından İzinli Kullanıcı'nın kim olacağı ve Uygulama kapsamındaki yetkileri belirlenecektir. Kullanıcı, İzinli Kullanıcı'nın Website ve Uygulama'ya erişim seviyesini her zaman ve bir nedene bağlı olmaksızın değiştirebilecek veya erişimini iptal edebilecektir. İzinli Kullanıcı ve Kullanıcı arasında Website ve Uygulama'ya erişime ilişkin olarak bir uyuşmazlık çıkması halinde İzinli Kullanıcı'nın Website, Uygulama veya İçerik'e erişimi yetkisine ilişkin kararı Kullanıcı verecektir.</p>
      <p>3.7. Kullanıcı, işbu sözleşme kapsamındaki Hizmetlerden yararlanmak için Website ve Uygulama'ya yüklediği her türlü İçerik'in mülkiyetinin ve İçerik'e ilişkin tüm sorumluluğun kendisinde olduğunu kabul, beyan ve taahhüt eder. Kullanıcı'nın işbu Sözleşme kapsamında sağladığı hizmet kapsamında MAPPERX'nin İçerik'i kullanma hakkı vardır. MAPPERX'in İçerik'e yahut İçerik'in yol açabileceği kayıp veya zararlara ilişkin herhangi bir sorumluluğu bulunmamaktadır. Kullanıcı, MAPPERX'in kayıp veriler de dahil olmak üzere bu kapsamda meydana gelebilecek zarar, ziyan ve kayıplardan herhangi bir sorumluluğu bulunmadığını kabul ve beyan eder.</p>
      <p>3.8. Website ve Uygulama'yı MAPPERX'in ve Üçüncü Şahısların bilgisayar ve ağ sistemlerine, yazılımlarına, cihazlarına ve bunların işlerliğine yahut bunlardan faydalanan diğer kullanıcıların faydalanmasına engel olacak, zarar verecek şekilde kullanmayacağını,</p>
      <p>3.8.1 Website ve Uygulama'ya hukuka aykırı İçerikler yüklemeyeceğini, kendisine tanınan erişim kapsamı dışında yetkisiz erişim sağlamayacağını,</p>
      <p>3.8.2. Uygulama ve Website'nin çalışmasında kullanılan bilgisayar programlarını, yazılımları kopyalamayacağını, değiştirmeyeceğini, çoğaltmayacağını, uyarlamayacağını, kaynak kodu oluşturmayacağını, tersine mühendislik işlemleri yapmayacağını kabul, beyan ve taahhüt eder.</p>
      <p>3.9. Uygulama'ya yüklenen içerikler ile ilgili her türlü sorumluluk Kullanıcı'ya aittir. MAPPERX, İçerik'in kaybının söz konusu olmayacağına dair garanti vermemektedir. MAPPERX, herhangi bir şekilde ortaya çıkabilecek İçerik kaybından sorumlu değildir.</p>
      <p>3.10. Kullanıcı, Uygulama'yı kullanmasının saklama kapasitesi ve aylık işlem sayısı dahil olmak üzere kısıtlamalara tabi olabileceğini kabul eder. Söz konusu kısıtlamalar Uygulama içinde belirtilecektir.</p>
      <p>3.11. Kullanıcı, Uygulama'ya ilişkin teknik sorunlar çıkması halinde MAPPERX ile iletişime geçmeden önce problemin tespit edilmesi ve çözümü için makul çabayı sarf edecektir. Kullanıcı'nın teknik destek ihtiyacının devam etmesi halinde gerekli destek Website, Uygulama yahut diğer uygun kanallar üzerinden sağlanacaktır.</p>
      <p>3.12. Kullanıcı, Website üzerinden iletişim araçları sağlanması durumunda bu iletişim araçlarını yalnızca hukuka uygun, MAPPERX ve Üçüncü Şahıslara zarar vermeyecek amaçlar çerçevesinde kullanacağını kabul, beyan ve taahhüt eder.</p>
      <p>3.13. MAPPERX, herhangi bir ön bildirimde bulunmaksızın işbu Sözleşme ve eklerini revize etme hakkına sahip olup bu hakkın kullanılması halinde ilgili değişiklik Kullanıcı tarafından Website ve/veya Uygulama'nın bir sonraki kullanımı ile birlikte yürürlüğe girecektir.</p>
      <p>3.14. MAPPERX, Kullanıcı'nın işbu Sözleşme hükümlerine ve Website kapsamında yer alan koşul ve şartlara aykırı davranması halinde Kullanıcı'nın üyeliğini askıya alabilir veya Sözleşme'yi feshederek kullanıcı hesabını sona erdirebilir. MAPPERX'in söz konusu aykırılıktan doğan zararlarını Kullanıcı'dan talep hakkı saklıdır.</p>
      <p>3.15. Kullanıcı tarafından MAPPERX ile paylaşılan bilgi ve veriler işbu Sözleşme'ye ek niteliğinde olan "Gizlilik Koşulları" kapsamında saklanacak ve kullanılacaktır. Kullanıcı, MAPPERX'in yürürlükteki mevzuat uyarınca yetkili makamlardan talep gelmesi halinde Kullanıcı'nın kendisinde bulunan bilgilerini ilgili yetkili makamlarla paylaşabileceğini kabul ve beyan eder. MAPPERX, Kullanıcı bilgilerini; kullanıcı güvenliği, kendi yükümlülüklerinin ifası ve bazı istatistikî değerlendirmeler için kayıt altına alabilir, işleyebilir, dilediği biçimde süresiz olarak yararlanabilir, kullanabilir.</p>
      <p>3.16.1. Kullanıcı, eğer varsa, Hizmet kapsamında MAPPERX'e ve/veya Uygulamaya ileteceği gerçek kişi Üçüncü Şahıslara ait kişisel verilerin işlenmesi, yurtiçinde ve yurtdışında Üçüncü Şahıslara aktarılması için ilgili kişilerden gerekli açık izinleri almaktan ve/veya gerekli koşulların karşılandığını teyit etmekten münhasıran sorumlu olduğunu ve kendisinin Veri Sorumlusu olduğunu; MAPPERX'in yalnızca Kullanıcı'nın talimat ve taleplerine göre hareket eden Veri İşleyen olacağını kabul etmiştir. Bu maddeye aykırılık ve Kullanıcı tarafından gereken izinlerin alınmaması sebebiyle Üçüncü Şahıslardan gelebilecek her türlü talep ve iddiadan Kullanıcı sorumlu olacak ve MAPPERX'i tüm taleplerden ari kılıp, tazmin edecektir.</p>
      <p>3.16.2. Varsa, Hizmete erişilebilmesi ve Hizmetin Üçüncü Şahıs Yazılımlarıyla çalışabilmesi için gerekli ön koşullar MAPPERX'in kurumsal web sitesinde duyurulmaktadır. Bu koşulların karşılanmasından; münhasıran Kullanıcı sorumludur.</p>
      <p><b>4. FİKRİ VE SINAİ HAKLAR</b></p>
      <p>4.1. Bu Sözleşme konusu Website ve Uygulama üzerindeki fikri mülkiyet ve/veya ticari lisans hakları MAPPERX'e ait olup, Fikir ve Sanat Eserleri Kanunu, Türk Ceza Kanunu, Sınai Mülkiyet Kanunu ve Türk Ticaret Kanunu hükümleri ile koruma altına alınmıştır. Kullanıcı'nın Website ve Uygulamayı işleme, değiştirme hakkı yoktur. Website ve Uygulama'nın bu maddeye aykırı olarak işlenmesi, değiştirilmesi halinde değiştirilmiş, işlenmiş Yazılımın fikri mülkiyet hakları dahil tüm hakları MAPPERX'e ait olur.</p>
      <p>4.2. Kullanıcı'ya işbu Sözleşme kapsamında Website ve Uygulama'yı, kendi dahili amaçları için kullanmak üzere, devredilemez, münhasır olmayan ve dünya çapında basit lisans verilmektedir. MAPPERX aynı ve benzer hizmetleri, Üçüncü Şahıslara verme ve Uygulama üzerindeki "mali/telif haklarını" dilediği biçimde kullanma hakkını saklı tutar. Bu Sözleşmede Kullanıcı'ya tanınan hak, MAPPERX'in Fikri Mülkiyet hakları dahil herhangi bir hakkını dilediği gibi kullanması önünde hiçbir sınırlama getirmez.</p>
      <p>4.2.1. Kullanıcı, MAPPERX'e işbu Sözleşme kapsamındaki hizmetlerin sağlanması ve diğer amaçlarla bilgilerinin ve İçerik'in kullanılması, kopyalanması, iletilmesi, saklanması için kullanım hakkı tanımaktadır. MAPPERX, hizmetlerin sağlanması amacıyla İçerik'e ilişkin olarak Üçüncü Şahıs geliştiricilere alt lisans verme hakkını haizdir.</p>
      <p>4.3. Kullanıcı, Uygulama ve Websiteyi herhangi bir şekilde kopyalayamaz, değiştiremez, çoğaltamaz, kaynak kodu haline getiremez, tersine mühendislik işlemlerine tâbi tutamaz, sırasını, işleyişini bozamaz, yapısal özelliklerini kopyalayamaz ve/veya bunları herhangi birinin bilgisine açamaz, ifşa edemez, sözleşme konusu amacı dışında kendi nam ve hesabına kullanamaz, Üçüncü Şahıslara kullandırtamaz.</p>
      <p>4.4. Kullanıcı, MAPPERX'nin ve/veya bağlı olduğu şirket(ler)in herhangi bir şekilde ticari unvanını, markasını, logosunu vs. kullanmayacaktır.</p>
      <p><b>5. MALİ HÜKÜMLER</b></p>
      <p>5.1. İşbu Sözleşme kapsamında yer alan Hizmetler, Kullanıcı'nın talebine istinaden ücretli veya ücretsiz olarak sunulabilmektedir. Ücretli ve ücretsiz Hizmetlerin kapsamına ilişkin açıklamalara Websitesi üzerinden erişilebilmekle birlikte söz konusu Hizmetler aşağıdaki koşullarda sunulacaktır;</p>
      <p>5.1.1. Ücretli Kullanım</p>
      <p>5.1.1.1 Kullanıcı, işbu Sözleşme konusu hizmetlerden Uygulama ve Website'sinde yer alan koşullar kapsamında, ücretleri belirtilen ödeme koşulları ve araçları ile tam ve eksiksiz olarak ödemesi halinde faydalanabilecektir.</p>
      <p>5.1.1.2 İşbu Sözleşme konusu hizmetlere ilişkin ücretler, ödeme koşulları, ücretlerin yürürlük tarihleri Uygulama ve Website'nin ilgili bölümlerinde ilan edilecektir. Kullanıcı, kendi isteğine bağlı olarak sisteme kredi yükleme hakkına sahiptir. Sözleşme'nin feshi de dahil olmak üzere üyeliğin herhangi bir nedenle sona ermesi halinde geri ödeme yapılmayacaktır.</p>
      <p>5.1.1.3 MAPPERX, Kullanıcı tarafından iletilen iletişim adresine siparişin başlangıcında söz konusu siparişe ilişkin kullanım ücretlerine ilişkin faturayı iletecektir.</p>
      <p>5.1.1.4 Kullanıcı, MAPPERX veya MAPPERX tarafından onaylanmış Üçüncü Şahıslar üyeliğe ve ödemeye ilişkin işlemler veya banka entegrasyonunu ve ilgili güncellemeleri gerçekleştirmek için Kullanıcı'nın kredi kartı ve ödeme bilgilerini saklayabileceğini kabul etmiştir.</p>
      <p><b>6. GARANTİ VE SORUMLULUK SINIRLARI</b></p>
      <p>6.1. MAPPERX, Uygulama'nın dijital ortamda sağlanan dokümantasyonuyla esaslı ölçüde uyum içinde olması için azami özeni göstermektedir. MAPPERX; Uygulama'nın kusursuz, hatasız, mükemmel olduğu ve Kullanıcı'nın özel ihtiyaçlarını ve/veya beklentilerini tamamen karşılayacağı şeklinde bir iddia ve taahhütte bulunmaz. Uygulama, Kullanıcı tarafından <i>olduğu gibi</i> kabul edilmelidir. MAPPERX; performans, belirli bir amaca uygunluk dahil ancak bunlarla sınırlı olmamak üzere açık veya zımni hiçbir bir özel garanti vermemektedir. Uygulama kullanmanın fayda ve zararları Kullanıcı'ya aittir.</p>
      <p>6.2. Uygulama'nın içerisinde Üçüncü Şahısların işlettiği web sitelerinden alınan bilgiler, parametreler bulunabilir. MAPPERX, bu bilgi ve parametrelerin doğruluğunu veya güvenliğini hiçbir koşulda taahhüt veya garanti etmez. İlgili Üçüncü Şahıs içeriklerinin ve söz konusu içerikler uyarınca hazırlanan veri, rapor ve benzeri bilgilerin doğruluğunun Kullanıcı tarafından teyit edilmesi gerekmektedir.</p>
      <p>6.3. Uygulama içinde yer alan Üçüncü Şahıs yazılımlarının lisans ve garanti koşulları, söz konusu yazılımların kendi orijinal lisans sözleşmelerine/koşullarına tabidir. MAPPERX'in, Üçüncü Şahıs yazılımlarına ilişkin performans, belirli bir amaca uygunluk dahil ancak bunlarla sınırlı olmamak üzere açık veya zımni herhangi bir garanti taahhüdü yoktur. Kullanıcı, Üçüncü Şahıs yazılımlarının lisans ve garanti koşullarına uygun davranacaktır.</p>
      <p>6.4. MAPPERX'in (i) Verilerdeki hata ve kayıplardan (ii) Voltaj dalgalanması ve elektrik kesilmesinden, virüs bulaşmasından, internet hatlarından ve benzeri çevresel faktörlerden kaynaklanan hatalardan; (iii) Uygulama kullanım eğitimi ve yerinde destek hizmetlerinden; (iv) Kullanıcı'nın yaptığı form ve rapor tasarımından; (v) Uygulama'nın yanlış veya mevzuata aykırı kullanılmasından; (vi) Hizmet Sağlayıcıları ile Veri Merkezlerinin ihmal ve kusurlarından; (vii) Donanım, işletim sistemi, uzaktan erişim ağı ve iletişim ağı (network) tasarımlarından, arızalarından, kesintilerinden ve bağlantı hatalarından; (viii) MAPPERX'e ait olmayan veri tabanı yazılımı ve diğer yazılım hatalarından, Üçüncü Şahıs yazılımlarından dolayı hiçbir hukuki sorumluluğu bulunmamaktadır. Kullanıcı, kendi çalışanlarının ihmal ve kusurlarından MAPPERX'e karşı müştereken ve müteselsilen sorumlu olacaktır.</p>
      <p>6.5. MAPPERX'in ağır kusur hali hariç olmak üzere; Uygulama'nın kullanımı ve bu Sözleşme nedeniyle ortaya çıkabilecek maddi veya manevi zararlarla, kayıplarla ve/veya taleplerle ilgili sorumluluğu; MAPPERX'e son satın alınan siparişi için varsa ödenen "Hizmet Bedeli" ile sınırlıdır. MAPPERX; mali sonuçlardan ve veri kaybı, kar-kazanç kaybı gibi dolaylı zararlardan, özel zararlardan ve/veya netice zararlarından ise hiçbir halde sorumlu değildir.</p>
      <p><b>7. FESİH</b></p>
      <p>7.1. Kullanıcı ücretsiz olarak Hizmetlerden faydalanıyor ise her zaman Sözleşmeyi sona erdirme hakkı bulunmakta olup Kullanıcı fesih tarihi itibariyle Website ve Uygulama'ya sadece erişebilecek olup Hizmetlerden yararlanamayacaktır.</p>
      <p>7.2. Kullanıcı ücretli olarak Hizmetlerden faydalanıyor ise hizmet süresi bitmeden, Sözleşmeyi sona erdirme hakkı bulunmamaktadır. Kullanıcı'nın bu Sözleşmeyi herhangi bir nedenle feshetmesi halinde, MAPPERX'e ödediği Hizmet Bedelinin kısmen ve/veya tamamen iadesini talep hakkı yoktur. Kullanıcı işbu Sözleşmeyi feshetmiş olsa da ödemesini yapmış olduğu hizmet süresi boyunca Hizmetlerden yararlanabilecektir. Kullanıcı, hizmet süresi sonu itibariyle Website ve Uygulama'ya sadece erişebilecek olup Hizmetlerden yararlanamayacaktır.</p>
      <p>7.2. MAPPERX, Sözleşme süresince herhangi bir zamanda Sözleşme konusu üyelik hizmetini elektronik posta ile Kullanıcı'ya bildirmek ve/veya kurumsal web sitesinde duyurmak kaydıyla tek taraflı olarak askıya alabilir, durdurabilir ve/veya üyelik hizmetini ve/veya bu Sözleşmeyi sona erdirebilir.</p>
      <p>7.3. MAPPERX, Kullanıcı hesabının 3 (üç) ay süresince kullanılmaması halinde işbu Sözleşme'yi herhangi bir bildirimde bulunmaksızın derhal feshedebilecektir.</p>
      <p><b>8. MÜCBİR SEBEPLER</b></p>
      <p>8.1. Mücbir Sebep Tanımı ve Etkileri: Eğer bir mücbir sebep (örneğin doğal afetler, savaş durumları, internet ve enerji kesintileri gibi öngörülemez ve karşı konulamaz olaylar) meydana gelirse ve bu durum Kullanıcı veya MAPPERX'in sözleşme yükümlülüklerini yerine getirmesini engellerse, bu durum yükümlülüklerin yerine getirilememesinden dolayı tarafların temerrüde düşmüş sayılmayacağı anlamına gelir. Taraflar ayrıca, mücbir sebep durumlarını sınırlamamış ve kanunun öngördüğünden daha geniş bir tanım kabul etmiştir.</p>
      <p>8.2. Yükümlülükler ve Bildirim: Mücbir sebep durumunda, etkilenen taraf diğer tarafa durumu derhal bildirmek, mücbir sebep sonucu yükümlülüklerin yerine getirilememesinin nedenlerini ortadan kaldırmak için gereken çabayı göstermek ve mücbir sebep ortadan kalktığında derhal yükümlülüklerini yerine getirmekle yükümlüdür.</p>
      <p>8.3. Sözleşmenin Feshi ve Zarar Ziyan Talebi: Mücbir sebep durumu iki aydan fazla sürerse, taraflardan herhangi biri sözleşmeyi tazminatsız olarak feshedebilir. Mücbir sebep nedeniyle, taraflar birbirlerinden herhangi bir zarar ziyan talebinde bulunamaz.</p>
      <p><b>9. ÇEŞİTLİ HÜKÜMLER</b></p>
      <p>9.1. Sözleşmenin Bütünlüğü: Sözleşmenin herhangi bir maddesinden vazgeçilmesi, iptal edilmesi, batıl sayılması, değiştirilmesi sözleşmenin iptal edilmesi şeklinde yorumlanmaz.</p>
      <p>9.2. Devir: Kullanıcı, MAPPERX'in önceden yazılı iznini almaksızın Sözleşmeden doğan hak ve yükümlülüklerini Üçüncü Şahıslara kısmen veya tamamen devir ve temlik edemez. Bu türden devirler, MAPPERX'e karşı hüküm ifade etmez. MAPPERX, Sözleşmeden doğan hak ve yükümlülüklerini kendi sermaye iştiraki veya hissedarlarının iştiraki olan Üçüncü Şahıslara devretmek hakkını haizdir.</p>
      <p>9.3. Kesin Delil Anlaşması: Anlaşmazlık halinde; Tarafların tutmuş olduğu e-posta yazışmaları ve Yazılıma ait Veri Merkezleri tarafından tutulan elektronik kayıtları kesin delil teşkil eder.</p>
      <p>9.4. Hakların Kullanılması: Bu Sözleşmeden doğan herhangi bir hakkın süresi içinde kullanılmamış olması, o haktan feragat edildiği anlamına gelmez.</p>
      <p>9.5. Yetki: Bu sözleşmeden doğacak anlaşmazlıklarda Ankara Merkez Mahkemeleri ve İcra Daireleri yetkilidir. Anlaşmazlıklarda Türk Hukuku uygulanır. Bu Sözleşmede geçen ifadelerin yorumu konusunda Fikir ve Sanat Eserleri Kanunu dikkate alınır.</p>
      <p>9.6. Tebligat: Bu Sözleşme ile ilgili tüm uyarı ve bildirimler Kullanıcı'nın etkinleştirme sırasında girmiş olduğu ya da bir şekilde MAPPERX'e bildirmiş olduğu elektronik posta adresine yapılır. Kullanıcı, bu adrese yapılan bildirimin yetkisiz kişilerce tebellüğ edildiği iddiasında bulunamaz. Bu elektronik posta adresine yapılan bildirimler hukuken geçerli tebligatın sonuçlarını doğurur. Taraflar, bu adrese yapılan tebligatlar iade edilse bile, hukuken geçerli tebligatla aynı sonucu doğuracağını kabul etmektedir. MAPPERX'in kurumsal web sitesinde yapılan duyurular da tebligat yerine geçer.</p>
      <p><b>GİZLİLİK KOŞULLARI</b></p>
      <p><b>10. GENEL</b></p>
      <p>Bu Websitesini ve içeriğindeki servisleri (“Hizmetler”) kullanıyor olmanız, BİRİZ GLOBAL TEKNOLOJİ LTD. ŞTİ. (“MAPPERX”) Websitesi Gizlilik Koşullarını (“Gizlilik Koşulları”) ve kurallarını okuduğunuz ve kabul ettiğiniz anlamına gelir. Gizlilik Koşullarında öngörülen zorunlulukları yerine getiremeyeceğinizi düşünüyorsanız, bu Websitesi veya Hizmetlerini kullanmayınız. Websitesindeki bazı yerlerin kullanımı veya bu yerlerle kurulacak etkileşim hakkında özel birtakım ek hüküm ve şartlar geçerli olabilir.</p>
      <p><b>11. GİZLİLİK KOŞULLARININ TAKİBİ/DEĞİŞİKLİK</b></p>
      <p>MAPPERX (“Site Sahibi”), herhangi bir zamanda önceden haber vermeksizin Gizlilik Koşullarında değişiklik yapma ya da ek koşullar getirme hakkına sahiptir. Kullanım sırasında toplanan bilgilerin niteliklerinden, nasıl kullanıldığından, bu bilgilerin Üçüncü Şahıslar ile hangi durumlarda paylaşıldığından ve gerekli tüm gizlilik koşullarından haberdar olunması için yapılan değişiklikler bu sayfada sunulacaktır. Site Sahibinin, Gizlilik Koşullarında değişiklik yapma hakkı saklı olduğundan, Gizlilik Koşullarının düzenli olarak takibi ve okunması Kullanıcının sorumluluğundadır. Bu Websitesi ve Hizmetlerini, yapılabilecek bu tarz bir değişiklikten sonraki kullanım, Gizlilik Koşullarındaki değişiklilerin kabul edildiği anlamını taşır.</p>
      <p><b>12. AÇIK SİSTEM</b></p>
      <p>Kullanıcılar; <i>(Kullanıcı tabiri, varsa, üyeler dahil, Websitesi'ne giren herkesi ifade eden genel bir tanım olarak kullanılmıştır.)</i> internet ortamının güvenilir bir ortam olmadığını, internet ortamında iletişimin riskli olduğunu, kişisel bilgiler, şifreler vb. de dâhil her türlü bilginin Üçüncü Şahısların hukuka aykırı fiillerinin muhatabı olabileceğini bilmekte ve kabul etmektedir. Site Sahibi, Websitesinin güvenli olduğu yönünde veya kötü niyetli hareketlerle ilgili olarak hiçbir garanti vermemektedir.</p>
      <p><b>13. KULLANICI BİLGİLERİ</b></p>
      <p>Kullanıcı tarafından Websitesi ve Hizmetlere yerleştirilen, iletilen veya bu Websitesi ve Hizmetler aracılığıyla gönderilen her türlü içerikten ve kişisel bilgiden <i>(her türlü yazı, doküman, müzik, ilan, reklâm, iletilen görüş ve düşünceler dâhil fakat bunlarla sınırlı olmamak üzere, ses veya yazı veya hareketli/hareketsiz görüntü içeren her türlü içerik)</i> Kullanıcı sorumludur. Kullanıcılar, Websitesi ve Hizmetlere ilettikleri/gönderdikleri her türlü bilginin güvenilirliğini, doğruluğunu, Üçüncü Şahısların haklarını ihlal etmediğini, yasalara aykırı olmadığını beyan ve garanti etmiştir. Site Sahibinin, Kullanıcılar tarafından web sitesine konulan, diğer Kullanıcılara veya Üçüncü Şahıslara herhangi bir zarar veya yük getirdiğine inandığı içeriği veya mevzuata, uluslararası hukuk belgelerine aykırı içeriği tamamen veya kısmen yayından kaldırma ya da erişimi engelleme hakkı saklıdır. Ancak bu yönde herhangi bir yükümlülüğü bulunmamaktadır.</p>
      <p><b>14. KULLANICI ADI VE ŞİFRE</b></p>
      <p>Site Sahibi bazı Hizmet ve bölümlerin kullanımını Üyelik/Kayıt şartına bağlı tutabilir. Kayıt sırasında Kullanıcıya ad ve şifre verilebilir ya da Kullanıcı tarafından ad ve şifre oluşturulması istenebilir. Kullanıcı adının ve şifrenin muhafazasından, yanlış ya da hukuka aykırı kullanımından ve olası tüm izinsiz kullanımlarından doğrudan Kullanıcı sorumludur. Girişi üyelik koşuluna bağlı Hizmetlere ancak şifre ile giriş yapılabilir. Şifrenin özel rakamlar, harfler ve karakterler kullanılarak daha güvenli bir biçimde oluşturulmasından ya da bunun için gerekli değişikliklerin yapılmasından Kullanıcı sorumludur. Üyelik adı ve şifre kullanılarak yapılan tüm işlemlerin sorumluluğu Kullanıcıya aittir. Üye adı ve şifrenin kaybedilmesi, yetkisiz Üçüncü Şahısların eline geçmesi ya da Üye güvenliğini tehdit eden bir durumla karşılaşılması halinde derhal Websitesine/Site Sahibine haber verilir.</p>
      <p><b>15. BİLGİLERİN KORUNMASI</b></p>
      <p>Site Sahibi, Websitesindeki tüm sayfaların güvenliği için azami gayret göstermektedir. Websitesinde kayıtlı bulunan verilerin gizliliğini, güvenliğini ve bütünlüğünü korumak için çok çeşitli teknik ve yönetimsel uygulamalardan yararlanılmaktadır.</p>
      <p><b>16. ÜÇÜNCÜ KİŞİLERE AİT SİTELER</b></p>
      <p>Bu Websitesinde, Site Sahibinin işletmediği veya işletimini kontrol etmediği, Üçüncü Şahıslar tarafından işletilen alt ve üst web siteleri bulunabilir ve bunlara bağlantı sağlanabilir/link/bilgi verilebilir. Site Sahibinin erişim sağlanan bu web sitelere ilişkin, içerik, güvenlik, gizlilik politikaları ve iletişimin sürekli sağlanacağına dair herhangi bir garantisi ya da özel bir taahhüdü yoktur. Sorumluluk, Üçüncü Şahıslara ait sitelerde yer alan güvenlik ve gizlilik koşullarına tabidir. Herhangi bir işlem yapılmadan önce söz konusu sitelerde yer alan güvenlik ve gizlilik koşulları okunmalıdır. Söz konusu sitelere sağlanan kişisel bilgilerden, bu sitelerden istifade edilen içerikten ve servislerden veya bu sitelerin gizlilik politika ve uygulamalarından Site Sahibi sorumlu tutulamaz.</p>
      <p><b>17. WEBSİTESİ YARDIMCI PROGRAMLARI</b></p>
      <p>Kullanıcının Websitesi tarafından sunulan bazı Hizmetlerden veya Websitesinden yararlanabilmesi için yardımcı programlar kullanılması gerekebilir. Bu Hizmetlerden/Websitesinden yararlanıldığı takdirde, Hizmetten yararlanma biçim ve kapsamıyla ilgili veriler, Websitesi veritabanına kaydedilebilir. Keza Hizmetlerden daha kolay yararlanabilmeniz için bazı "çerez"lerden yararlanılabilir, bunlar vasıtasıyla Kullanıcıya bazı bilgiler gönderilebilir.</p>
      <p><b>18. KİŞİSEL BİLGİLER</b></p>
      <p>18.1. Websitesinin ziyaret edilmesi, kullanılması ya da herhangi bir Hizmetten yararlanılması için ad, soyad, adres/yaşanılan yer, IP bilgileri, e-posta adresi, telefon numarası v.b. kişisel bilgiler Websitesine verilmiş, kaydedilmiş olur/olabilir. Kullanıcı, vermiş/açıklamış/kaydetmiş olduğu kişisel bilgilerin Site Sahibine açık olacağını dikkate alarak bu bilgileri açıklamış olduğunu ve Websitesine açıkladığı, kaydettiği her bilginin, içeriğin Site Sahibine karşı gizliliğini yitirdiğini kabul etmiş sayılır. Kullanıcı, kişisel bilgilerini diğer kullanıcılarla veya Üçüncü Şahıslara paylaşmayı seçerse, kaydettiği/ilettiği her bilgi ve içeriğin diğer kullanıcılara ve Üçüncü Şahıslara karşı da gizliliğini yitirdiğini kabul etmiş sayılır.</p>
      <p>18.2. Site Sahibi, Kullanıcı tarafından verilmiş olan bilgileri ve kaydedilen içeriği veritabanlarında tasnif edip saklayabilir, Websitesinin, Site Sahibinin faaliyet alanındaki işlerin ve Hizmetlerin amaçlarıyla uyumlu olarak kullanabilir, işleyebilir, mevzuata uygun olarak yurt içine ya da yurt dışına transfer edebilir, veritabanındaki verilerden dilediği gibi yararlanabilir. Kullanıcı bu konuda Site Sahibine açıkça izin vermiştir. Site Sahibi, Websitesi aktivite bilgilerinden, erişim araçlarından ve browser bilgilerinden de dilediği gibi yararlanma hakkına sahiptir.</p>
      <p>18.3. Hassas Bilgiler: Site Sahibi, Kullanıcılardan yasalar gerektirmediği sürece herhangi bir şekilde ve kesinlikle; ırk ve etnik kimlik, dini/siyasi/felsefi düşünce, fiziksel ya da ruhsal sağlık ve özellikler gibi hassas bir bilgi talep etmemektedir. Bu bilgilerin verilmiş, kaydedilmiş olmasından dolayı Site Sahibinin bir sorumluluğu yoktur.</p>
      <p>18.4. Kişisel verilerinizle ilgili olarak verdiğiniz izin, size hizmet vermek; Hizmetlerin, Site Sahibinin, üyelerin, Üçüncü Şahısların tanıtım faaliyetleri; hukuki gereklilikler vb. hallerde kullanma iznini de içermektedir.</p>
      <p><b>19. TİCARİ İLETİŞİM</b></p>
      <p>MAPPERX, Websitesine veya kendisine iletilmiş ya da bir şekilde kaydedilmiş/kaydettirilmiş olan iletişim adresine, elektronik ileti veya ticari elektronik ileti gönderebilir. Ticari nitelikte olsun ya da olmasın, her türlü elektronik iletişim aracılığıyla gönderilecek elektronik iletinin gönderimine önceden izin/onay verdiğiniz kabul edilir. Vermiş olduğunuz izni/onayı iptal etme ve ticari nitelikteki elektronik iletileri reddetme hakkını her zaman kullanabilirsiniz. Red talepleri MAPPERX tarafından en geç on (10) iş günü içinde işleme alınacaktır. Ret yolları, göndericisinin MAPPERX olduğu elektronik iletilerde gösterilir.</p>
      <p><b>20. GİZLİLİK KOŞULLARININ İHLALİ</b></p>
      <p>Site Sahibi, Gizlilik Koşullarına uyulmaması ya da kuralları ihlal etme girişiminde bulunulması durumunda, ihlal tam olarak gerçekleşsin ya da gerçekleşmesin, sistemde mevcut bilgileri reddetme, içerikten çıkarma, silme hakkıyla birlikte önceden haber vermeksizin Kullanıcıların Websitesi ve Hizmetlere erişimini askıya alma, sonlandırma, üyeliği iptal etme hakkını (zorunlu olmamakla birlikte) saklı tutar. Bu kural, koşulların Kullanıcı tarafından dolaylı ihlali ya da ihlal girişimi olması durumu için de geçerlidir.</p>
      <p><b>21. BİLGİ VE İLETİŞİM</b></p>
      <p><a href="https://isbasi.com/" rel="nofollow noopener" target="_blank">mapperx.com</a> web sitesinin gizlilik koşullarına ilişkin sorularınız için <a href="mailto:support@mapperx.com">support@mapperx.com</a> adresine yazarak daha fazla bilgi alabilirsiniz</p>
    </div>
  </div>
);

export default GizlilikPolitikasiPage; 


